### ISSUE TITLE
Chinese support json

### ISSUE THREAD

**Issue by sasukebinbin** [dckiller51/lovelace-body-miscale-card#15]
Kindly help to add Chinese translate. 
Attached cn.json. 

[cn.json.zip](https://github.com/dckiller51/lovelace-body-miscale-card/files/7176446/cn.json.zip)

**Comment by dckiller51** [comment]
> Kindly help to add Chinese translate.
> Attached cn.json.
> 
> [cn.json.zip](https://github.com/dckiller51/lovelace-body-miscale-card/files/7176446/cn.json.zip)

Hello, thank you for your contribution. You can try version 5.6.3 via hacs

**Comment by sasukebinbin** [comment]
Hi just updated. But not auto change base on HA setting. How to manually set language?

**Comment by dckiller51** [comment]
The language in HA is cn ?

**Comment by sasukebinbin** [comment]
Yes

**Comment by dckiller51** [comment]
Can you give me another card for which it works?

**Comment by sasukebinbin** [comment]
What you mean another card?

**Comment by dckiller51** [comment]
I would like to verify that this is cn I wonder if it is not zh_cn? So with a card for which it works for you I could compare.

**Comment by sasukebinbin** [comment]
custom:mini-media-player

**Comment by sasukebinbin** [comment]
Is this what you want? 
![image](https://user-images.githubusercontent.com/36916438/133750219-3149b4a1-8648-486b-b4ce-245596ad0f19.png)

**Comment by sasukebinbin** [comment]
It will show chinese text to ask enter Text for speach

**Comment by dckiller51** [comment]
I think it is rather zh-Hant.json or zh-Hans.json 
https://github.com/home-assistant/core/tree/dev/homeassistant/components/media_player/translations

**Comment by sasukebinbin** [comment]
Got you. cn.json is just a name I define myself. From the link I think the name should be zh-Hans. 
s = Simplified Chinese
t = Traditionoal Chinese

**Comment by sasukebinbin** [comment]
My Ha is set to Simplified Chinese

**Comment by dckiller51** [comment]
简体中文 ?

**Comment by sasukebinbin** [comment]
Yes

**Comment by dckiller51** [comment]
I just pushed it works now

**Comment by sasukebinbin** [comment]
I updated but still cannot show. I have tried clear cache and open in private window. And also uninstall and reinstall in hacs.. 
But nothing changed.

**Comment by sasukebinbin** [comment]
Please help if have time. Thanks a lot

**Comment by dckiller51** [comment]
> Please help if have time. Thanks a lot

sorry i left for work

**Comment by sasukebinbin** [comment]
Np. I resolved by reinstall via hacs. Thanks. 
Hope the user button can work soon.
