### ISSUE TITLE
Image and Icons not shown

### ISSUE THREAD

**Issue by FPMilan** [dckiller51/lovelace-body-miscale-card#20]
Hi,
for me the image is not showing and neither the icons are.
I have copied the image into ~/config/www/images/ and the Icons to ~/config/www/images/bodyscoreIcon/

In the card config I have set the path as /local/images/miscale2.jpg or /local/miscale2.jpg both do not work. Any tips? Probably I just can not type the right path I guess.

**Comment by dckiller51** [comment]
It's good.

![Screenshot_2021-11-27-20-11-31-160_io homeassistant companion android](https://user-images.githubusercontent.com/53062806/143719295-576a205b-90ae-4b1e-a870-f7c837ee7cba.jpg)

**Comment by dckiller51** [comment]
![IMG_20211127_201410](https://user-images.githubusercontent.com/53062806/143719381-341bcfa6-0b38-46ef-88ca-90c0c74e2214.jpg)

**Comment by jerry-ch-issue** [comment]
![image](https://user-images.githubusercontent.com/65878337/146147071-cfb50f6a-58c7-4c53-ba42-41505adcc979.png)
![image](https://user-images.githubusercontent.com/65878337/146147141-01368d0a-e4b5-4f27-a085-89b73a370de5.png)
![image](https://user-images.githubusercontent.com/65878337/146147213-4b4ec9cd-a346-40e7-a66c-2cdebafe1596.png)
![image](https://user-images.githubusercontent.com/65878337/146147935-834110c9-d50d-48b2-8112-ad71e263d6ec.png)
similar issues. I can see images but icons. 

And the language has not been automatically changed to zh-hans.

**Comment by xpavli44** [comment]
I've noticed something about the miscale2.jpg. It is named as *.**jpg** but if I download it via browser it saves as *.**jpeg**. I suspect that might cause some issues. @dckiller51 WDYT?
![Screenshot 2021-12-22 at 9 33 50](https://user-images.githubusercontent.com/3585733/147062921-9a3f878f-2b69-47f2-9218-f8fb836ea97a.png)

**Comment by FPMilan** [comment]
For me the issue with the background image is solved. The file was somehow corrupted and a redownload solved it. 
Regarding the Icons, I realized, that they are only visible in dark mode. Would be great if you could change the Icons to work for both themes. Thank you for the replies and help!

**Comment by jerry-ch-issue** [comment]
> 



> For me the issue with the background image is solved. The file was somehow corrupted and a redownload solved it. Regarding the Icons, I realized, that they are only visible in dark mode. Would be great if you could change the Icons to work for both themes. Thank you for the replies and help!

No, I change to dark mode. The icons still can't be displayed.

**Comment by dckiller51** [comment]
I'll see what I can do.
